import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geomanist = localFont({
  src: [
    // Correct paths relative to the 'app' directory
    {
      path: "./assets/fonts/GeomanistThin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./assets/fonts/GeomanistExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./assets/fonts/GeomanistLight.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./assets/fonts/GeomanistBook.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./assets/fonts/GeomanistRegular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./assets/fonts/GeomanistMedium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./assets/fonts/GeomanistBold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./assets/fonts/GeomanistBlack.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./assets/fonts/GeomanistUltra.ttf",
      weight: "900",
      style: "normal",
    }, // 900 is the max standard weight
  ],
  variable: "--font-geomanist", // This variable now represents the whole family
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${geomanist.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
